const data = {
  professionals: [
    {
      _id: '1',
      name: 'Omar AbdAllah',
      category: 'Home',
      image: '/images/p1.jpg',
      price: 620,
      skills: 'build house and other things...',
      experience: 3,
      nbOfJobs:10,
      location: "Gafsa - Gafsa South",
      dateOfBirth: "12/15/1996",
      brand: 'Build',
      about:"With over 20 years of experience in interior painting, we can paint your home with quality and speed. Also carrying out other small works and repairs.",
      rating: 4.5,
      numReviews: 10,
      description: 'skillful builder',
      availdaybegin: 'sat', 
      availdayend: 'fri', 
      starthours: 6,
      endhours: 18
    },
    {
      _id: '2',
      name: 'Hadi nadi',
      category: 'Well-being',
      image: '/images/p14.jpg',
      price: 230,
      skills: 'pet dogs and other animals...',
      experience: 6,
      nbOfJobs:10,
      location: "Gafsa - Gafsa South",
      dateOfBirth: "12/15/1996",
      brand: 'Pet Sitting',
      about:"With over 20 years of experience in interior painting, we can paint your home with quality and speed. Also carrying out other small works and repairs.",
      rating: 3.5,
      numReviews: 12,
      description: 'skillfull Pet Sitting',
      availdaybegin: 'mon', 
      availdayend: 'sat',  
      starthours: 6,
      endhours: 18
    },
    {
      _id: '3',
      name: 'Riath Mehriz',
      category: 'Events',
      image: '/images/p15.jpg',
      price: 230,
      skills: 'photographer for wedding and blah blah blah...',
      experience: 6,
      nbOfJobs:10,
      location: "Gafsa - Gafsa South",
      dateOfBirth: "12/15/1996",
      brand: 'photographers',
      about:"With over 20 years of experience in interior painting, we can paint your home with quality and speed. Also carrying out other small works and repairs.",
      rating: 3.5,
      numReviews: 12,
      description: 'skillfull photographer',
      availdaybegin: 'thu', 
      availdayend: 'sat', 
      starthours: 18,
      endhours: 23
    },
    {
      _id: '4',
      name: 'Sami Agerbi',
      category: 'Classes',
      image: '/images/p16.jpg',
      price: 230,
      skills: 'painting teacher and blah blah blah...',
      experience: 8,
      nbOfJobs:10,
      location: "Gafsa - Gafsa South",
      dateOfBirth: "12/15/1996",
      brand: 'painting teacher',
      about:"With over 20 years of experience in interior painting, we can paint your home with quality and speed. Also carrying out other small works and repairs.",
      rating: 4.5,
      numReviews: 32,
      description: 'skillfull painting teacher',
      availdaybegin: 'thu', 
      availdayend: 'sat', 
      starthours: 6,
      endhours: 18
    },
    {
      _id: '5',
      name: 'Sara Tara',
      category: 'Companies',
      image: '/images/p12.jpg',
      price: 230,
      skills: 'secretary and blah blah blah...',
      experience: 8,
      nbOfJobs:10,
      location: "Gafsa - Gafsa South",
      dateOfBirth: "12/15/1996",
      brand: 'secretary',
      about:"With over 20 years of experience in interior painting, we can paint your home with quality and speed. Also carrying out other small works and repairs.",
      rating: 4.5,
      numReviews: 32,
      description: 'skillfull secretary ',
      availdaybegin: 'sat', 
      availdayend: 'fri', 
      starthours: 8,
      endhours: 18
    },
    {
      _id: '6',
      name: 'Majdi ElAgerbi',
      category: 'Companies',
      image: '/images/p17.jpg',
      price: 230,
      skills: 'Lawyer and blah blah blah...',
      experience: 8,
      nbOfJobs:3,
      location: "Gafsa - Gafsa North",
      dateOfBirth: "12/15/1992",
      brand: 'Lawyers',
      about:"With over 20 years of experience in interior painting, we can paint your home with quality and speed. Also carrying out other small works and repairs.",
      rating: 4.5,
      numReviews: 32,
      description: 'skillfull Lawyer ',
      availdaybegin: 'sun', 
      availdayend: 'wed', 
      starthours: 8,
      endhours: 19
    },
  ],
};
export default data;
